name: CI

on:
  push:
    branches: [main]  
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
        
    - name: Change directory
      run: cd ts-micro-app
        
    - name: Checkout tag
      run: git checkout p1.3
        
    - name: Install dependencies
      run: yarn install
